name: Check no illegal files changed
on:
  pull_request:
    branches:
      - main
jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@823fcebdb31bb35fdf2229d9f769b400309430d0 # v46
        with:
          dir_names: "true"

      - name: Fail if more changed that just a new order
        if: steps.changed-files.outputs.all_changed_and_modified_files_count != '1' || steps.changed-files.outputs.added_files_count != '1' || ! contains(steps.changed-files.outputs.added_files, 'Orders')
        run: fail 1