name: Create and comment payment link
on:
  pull_request:

jobs:
  comment-payment-link:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Get order file name
        id: changed-files
        uses: tj-actions/changed-files@823fcebdb31bb35fdf2229d9f769b400309430d0 # v46

      - name: Prepare order file for script
        env:
          orderFile: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
        run: mv $orderFile currentOrder.yaml

      - name: Run createPaymentLink script
        id: create_link
        run: ./main/.github/workflows/scripts/createPaymentLink ${{secrets.STRIPE_TOKEN}}

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Here is your payment link: ${{ steps.create_link.outputs.payment_link }}'
            })